// 17 landing page di koleksi. Deskripsi, jumlah halaman, dan fitur mengikuti isi tiap template (1 Okt 2026);
// tangkapan layar diambil dari demo live.
export const templates = [
  { name: 'Nimbus', kategori: 'Click-Through', terjual: 0, description: 'Cloud lokal dengan halaman status 90 hari dan laporan insiden terbuka.', halaman: 4, sorot: 'Kalkulator harga', image: '/images/landing/nimbus.webp', url: 'https://landing-nimbus.vercel.app' },
  { name: 'EduPlay', kategori: 'Click-Through', terjual: 0, description: 'Aplikasi matematika SD kelas 1–3, sepuluh menit sehari.', halaman: 3, sorot: 'Dua permainan bisa dimainkan', image: '/images/landing/eduplay.webp', url: 'https://landing-eduplay.vercel.app' },
  { name: 'Cissy Coffee', kategori: 'Profil', terjual: 6, description: 'Kedai kopi di Malang dengan papan menu kapur yang ditulis ulang tiap pagi.', halaman: 5, sorot: 'Papan menu & kopi untuk acara', image: '/images/landing/cissycoffee.webp', url: 'https://landing-cissycoffee.vercel.app' },
  { name: 'SanzyHub', kategori: 'Platform', terjual: 2, description: 'Toko template landing page dengan dasbor katalog yang dihitung dari data.', halaman: 3, sorot: 'Katalog bersaring & lisensi', image: '/images/landing/sanzyhub.webp', url: 'https://landing-sanzyhub.vercel.app' },
  { name: 'Tasty Corner', kategori: 'Lead Gen', terjual: 1, description: 'Struk Mingguan: satu menu F&B dibedah sampai rupiah terakhir.', halaman: 4, sorot: 'Kalkulator food cost', image: '/images/landing/tastycorner.webp', url: 'https://landing-tastycorner.vercel.app' },
  { name: 'Rasa Nusantara', kategori: 'Lead Gen', terjual: 1, description: 'Kartu resep terstandar untuk dapur restoran — gramasi, titik kritis, HPP.', halaman: 3, sorot: 'Penskala porsi 1–200', image: '/images/landing/rasanusantara.webp', url: 'https://landing-rasanusantara.vercel.app' },
  { name: 'CitaRasa Digital', kategori: 'Lead Gen', terjual: 2, description: 'Memindahkan rumah makan legendaris ke ponsel pelanggan, dengan studi kasus.', halaman: 3, sorot: 'Tiga studi kasus', image: '/images/landing/citarasa.webp', url: 'https://landing-citarasa.vercel.app' },
  { name: 'SkyWings', kategori: 'Produk', terjual: 0, description: 'Maskapai antarkota dengan jadwal jam setempat dan papan keberangkatan.', halaman: 7, sorot: 'Pencarian boarding pass', image: '/images/landing/skywings.webp', url: 'https://landing-skywings.vercel.app' },
  { name: 'Bribu', kategori: 'Platform', terjual: 3, description: 'Papan brief desain: tiga desainer dibayar untuk sketsa, klien memilih satu.', halaman: 4, sorot: 'Pratinjau kartu brief', image: '/images/landing/bribu.webp', url: 'https://landing-bribu.vercel.app' },
  { name: 'LuxeElectro', kategori: 'Sales', terjual: 3, description: 'Toko audio dengan lembar spesifikasi lengkap dan uji dengar 14 hari.', halaman: 3, sorot: 'Bandingkan kurva frekuensi', image: '/images/landing/luxeelectro.webp', url: 'https://landing-luxeelectro.vercel.app' },
  { name: 'Modewear', kategori: 'Sales', terjual: 1, description: 'Pra-pesan kapsul pakaian kerja yang dijahit setelah dipesan.', halaman: 4, sorot: 'Hitung mundur & pencari ukuran', image: '/images/landing/modewear.webp', url: 'https://landing-modewear.vercel.app' },
  { name: 'Woodora', kategori: 'Sales', terjual: 0, description: 'Furnitur kayu solid sesuai ukuran, lengkap dengan gambar kerja.', halaman: 4, sorot: 'Pratinjau ukuran langsung', image: '/images/landing/woodora.webp', url: 'https://landing-woodora.vercel.app' },
  { name: 'Zychrome', kategori: 'Webinar', terjual: 0, description: 'Webinar 95 menit dengan enam titik interaksi dan papan hasil.', halaman: 3, sorot: 'Polling & kuis bisa dicoba', image: '/images/landing/zychrome.webp', url: 'https://landing-zychrome.vercel.app' },
  { name: 'Lumicast', kategori: 'Webinar', terjual: 0, description: 'Siaran pelatihan untuk pengurus organisasi dengan rundown tercetak.', halaman: 3, sorot: 'Cek perangkat interaktif', image: '/images/landing/lumicast.webp', url: 'https://landing-lumicast.vercel.app' },
  { name: 'NextTalks', kategori: 'Webinar', terjual: 1, description: 'Empat pembicara, satu meja, tiap Kamis kedua — plus arsip transkrip.', halaman: 5, sorot: 'Arsip bisa dicari', image: '/images/landing/nexttalks.webp', url: 'https://landing-nexttalks.vercel.app' },
  { name: 'Elevinar', kategori: 'Webinar', terjual: 7, description: 'Webinar yang dijalankan seperti pertunjukan, dengan denah kursi.', halaman: 3, sorot: 'Buku acara siap cetak', image: '/images/landing/elevinar.webp', url: 'https://landing-elevinar.vercel.app' },
  { name: 'Sribu (konsep redesain)', kategori: 'Platform', terjual: 4, description: 'Konsep redesain tidak resmi: kontes desain sebagai sayembara, dengan catatan redesain.', halaman: 2, sorot: 'Simulasi “Coba jadi juri”', image: '/images/landing/sribu.webp', url: 'https://landing-sribu.vercel.app' },
];
