export const templates = [
  { name: 'Nimbus Cloud', kategori: 'Click-Through', description: 'Landing cloud SaaS — dorong pengunjung ke uji coba gratis 14 hari.', image: '/images/l1.png', url: 'https://nimbus.pintuweb.com' },
  { name: 'EduPlay', kategori: 'Click-Through', description: 'Aplikasi edukasi & game imersif — belajar sambil bermain.', image: '/images/l2.png', url: 'https://eduplay.pintuweb.com' },
  { name: 'Cissy Coffee', kategori: 'Profil', description: 'Company profile kedai kopi premium dengan suasana cozy.', image: '/images/l3.png', url: 'https://cissycoffee.pintuweb.com' },
  { name: 'SanzyHub', kategori: 'Platform', description: 'Hub jasa & template website premium, lengkap dengan alur pembayaran.', image: '/images/l4.png', url: 'https://sanzyhub.pintuweb.com' },
  { name: 'Tasty Corner', kategori: 'Lead Gen', description: 'Lead generation F&B gelap nan berani — ubah audiens jadi pelanggan.', image: '/images/l5.png', url: 'https://tastycorner.pintuweb.com' },
  { name: 'Rasa Nusantara', kategori: 'Lead Gen', description: 'Kuliner tradisional dengan sentuhan modern yang menggugah.', image: '/images/l6.png', url: 'https://rasanusantara.pintuweb.com' },
  { name: 'CitaRasa Digital', kategori: 'Lead Gen', description: 'Retro 1985 — solusi digital untuk bisnis kuliner klasik.', image: '/images/l7.png', url: 'https://citarasa.pintuweb.com' },
  { name: 'SkyWings', kategori: 'Produk', description: 'Maskapai modern — rasakan keajaiban terbang, pesan tiket mudah.', image: '/images/l8.png', url: 'https://skywings.pintuweb.com' },
  { name: 'Bribu', kategori: 'Platform', description: 'Platform kontes desain — temukan desainer berbakat secara online.', image: '/images/l9.png', url: 'https://bribu.pintuweb.com' },
  { name: 'LuxeElectro', kategori: 'Sales', description: 'Elektronik premium beraksen ungu untuk hidup lebih mewah.', image: '/images/l10.png', url: 'https://luxeelectro.pintuweb.com' },
  { name: 'MODEWEAR', kategori: 'Sales', description: 'Fashion editorial — koleksi terbaru untuk semua musim.', image: '/images/l11.png', url: 'https://modewear.pintuweb.com' },
  { name: 'Woodora', kategori: 'Sales', description: 'Furnitur kayu solid untuk rumah impian yang hangat.', image: '/images/l12.png', url: 'https://woodora.pintuweb.com' },
  { name: 'Zychrome', kategori: 'Webinar', description: 'Webinar interaktif untuk mengasah skill dari para ahli.', image: '/images/l13.png', url: 'https://zychrome.pintuweb.com' },
  { name: 'Lumicast', kategori: 'Webinar', description: 'Menerangi pikiran — webinar eksklusif untuk masa depanmu.', image: '/images/l14.png', url: 'https://lumicast.pintuweb.com' },
  { name: 'NextTalks', kategori: 'Webinar', description: 'Ide besar & pembicara inspiratif dalam satu platform.', image: '/images/l15.png', url: 'https://nexttalks.pintuweb.com' },
  { name: 'Elevinar', kategori: 'Webinar', description: 'Naikkan level wawasanmu lewat sesi yang meledakkan semangat.', image: '/images/l16.png', url: 'https://elevinar.pintuweb.com' },
  { name: 'Sribu Redesign', kategori: 'Platform', description: 'Redesign landing Sribu — platform kontes desain terbaik.', image: '/images/l17.png', url: 'https://sribu.pintuweb.com' },
];
